import turtle,time
yy=turtle.Turtle()
yy.color('yellow')
yy.forward(100)
time.sleep(1)
yy.left(90)
yy.forward(100)
time.sleep(1)
yy.left(90)
yy.forward(100)
time.sleep(1)
yy.left(90)
yy.forward(100)
time.sleep(1)
yy.left(90)
